route:
  name: api
smcp:
  productionMode: false # Configures Jaeger storage to use Memory or Elasticsearch
  gateways:
    enabled: true
    egress:
      enabled: false
    ingress:   
      enabled: true
      runtime:
        container:
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits: {}
        deployment:
          autoScaling:
            enabled: true
    additionalIngress: {}
    additionalEgress: {}
    openshiftRoute:
      enabled: false

