namespaceMemberSelector:
  istio.io/rev: ossm2
smcp:
  name: ossm2
  accessLoggingEnabled: true
  version: v2.6
  mode: ClusterWide # MultiTenant
  outboundPolicy: REGISTRY_ONLY # ALLOW_ANY
  discoverySelectors:
    - matchExpressions:
      - key: maistra.io/member-of
        operator: Exists
    # - matchLabels:
    #     # Allow any namespaces with `istio-discovery=enabled`
    #     istio-discovery: enabled
tempo:
  enabled: true
  host: tempo-minio-dev-distributor.tempo-system.svc.cluster.local
kiali:
  enabled: false
istiod:
  replicas: 2
