groups:
- name: cert-manager-certificates
  rules:
  - alert: CertManagerCertExpired
    annotations:
      description: |-
        The certificate expired after {{ $value | humanizeDuration }}.
        VALUE = {{ $value }}
        LABELS = {{ $labels }}
      summary: |-
        The cert `{{ $labels.name }}` has expired since {{ $value | humanizeDuration }}.
    expr: |-
      sum by (exported_namespace, name) 
      (certmanager_certificate_expiration_timestamp_seconds) <= time()
    for: 1h
    labels:
      severity: critical
  - alert: CertManagerCertExpirySoon
    annotations:
      description: |-
        The certificate will soon expire after {{ $value | humanizeDuration }} and should have been renewed by now.
        This Alert starts firing after 1/3 of the renewal time period before the expiration has passed.
        VALUE = {{ $value }}
        LABELS = {{ $labels }}
      summary: |-
        The cert `{{ $labels.name }}` is {{ $value | humanizeDuration }} from expiry. It should have been renewed by now.
    expr: |-
      sum by (exported_namespace, name)
      (certmanager_certificate_expiration_timestamp_seconds - time() <=
      (certmanager_certificate_expiration_timestamp_seconds - certmanager_certificate_renewal_timestamp_seconds) - (certmanager_certificate_expiration_timestamp_seconds - certmanager_certificate_renewal_timestamp_seconds) / 3)
    for: 1h
    labels:
      severity: warning
  - alert: CertManagerCertNotReady
    annotations:
      description: |-
        This certificate has not been issued for at least 10m.
        You may be using a previously minted certificate in the meantime, however you need to make sure this finishes successfully before the expiration time.
        VALUE = {{ $value }}
        LABELS = {{ $labels }}
      summary: The cert `{{ $labels.name }}` is not ready.
    expr: |-
      max by (name, exported_namespace, condition) (
        certmanager_certificate_ready_status{condition!="True"} == 1
      )
    for: 10m
    labels:
      severity: critical
