groups:
- name: istio:circuit_breaker
  interval: 10s
  rules:
  - record: istio:circuit_breaker:external_requests:rate1m
    expr: |
      rate(istio_requests_total[1m])
      unless ignoring(__dst__)
      (label_replace(istio_requests_total, "__dst__", "$1", "source_cluster", "(.*)") == label_replace(istio_requests_total, "__dst__", "$1", "destination_cluster", "(.*)"))
- name: circuit-breaker
  interval: 10s
  rules:  
  - alert: CircuitBreakerTripped
    annotations:
      description: |-
        The circuit was tripped and the request was routed to another cluster. The responses are apparently successful (not 5xx server error codes). You still should investigate why the circuit was tripped.  
          VALUE = {{ $value }}
          LABELS = {{ $labels }}
      source_app: |-
        {{ $labels.source_app }}
      destination_cluster: |-
        {{ $labels.destination_cluster }}
      destination_service: |- 
        {{ $labels.destination_service }}
      response_code: |-
        {{ $labels.response_code }}
      response_flags: |-
        {{ $labels.response_flags }}
      summary: Traffic has been redirected to a different cluster, but is apparently working
    expr: |-
      sum(istio:circuit_breaker:external_requests:rate1m{response_code!~"5.*"}) by (destination_cluster, destination_service, response_code, response_flags, source_app) > 0
    for: 1m
    labels:
      severity: warning
  - alert: CircuitBreakerTrippedAndFailing
    annotations:
      description: |-
        The circuit was tripped and the request was routed to another cluster. The responses are apparently unsuccessful (5xx server error codes). You are most likely experiencing downtime.
          VALUE = {{ $value }}
          LABELS = {{ $labels }}
      source_app: |-
        {{ $labels.source_app }}
      destination_cluster: |-
        {{ $labels.destination_cluster }}
      destination_service: |- 
        {{ $labels.destination_service }}
      response_code: |-
        {{ $labels.response_code }}
      response_flags: |-
        {{ $labels.response_flags }}
      summary: Traffic has been redirected to a different cluster, but is apparently working
    expr: |-
      sum(istio:circuit_breaker:external_requests:rate1m{response_code=~"5.*"}) by (destination_cluster, destination_service, response_code, response_flags, source_app) > 0
    for: 1m
    labels:
      severity: critical
