apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-for-tempo
  annotations:
    argocd.argoproj.io/sync-wave: '4'
spec:
  host: {{ .Values.tempo.host }}
  trafficPolicy:
    tls:
      mode: DISABLE
