{{- with .Values.route }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .name }}
spec:
  port:
    targetPort: http2
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  wildcardPolicy: None
{{- end }}
