apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: tempo-otlp-http
  annotations:
    argocd.argoproj.io/sync-wave: '4'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  hosts:
  - {{ .Values.tempo.host }}
  location: MESH_EXTERNAL
  ports:
  - number: 4317
    name: otlp-grpc
    protocol: GRPC
  resolution: DNS
