---
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: ossm-2-5
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  version: v2.5
  mode: ClusterWide
  meshConfig:
    discoverySelectors:
      - matchLabels:
          {{- .Values.namespaceMemberSelector | toYaml | nindent 10 }}
    extensionProviders:
      - name: tempo
        opentelemetry:
          service: {{ .Values.tempo.host }}
          port: 4317
  tracing:
    sampling: 10000
    type: None
  security:
    dataPlane:
      mtls: true
      automtls: true
    controlPlane:
      mtls: true
  proxy:
    {{- if .Values.smcp.accessLoggingEnabled }}
    accessLogging:
      file:
        name: /dev/stdout
    {{- end }}
    networking:
      trafficControl:
        outbound:
          policy: REGISTRY_ONLY # ALLOW_ANY
  gateways:
    enabled: false
    egress:
      enabled: false
    ingress:   
      enabled: false
    openshiftRoute:
      enabled: false
  addons:
    grafana:
      enabled: false
    kiali:
      enabled: false
    prometheus:
      enabled: false
