apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  annotations:
    argocd.argoproj.io/sync-wave: '4'
spec:
  tracing:
  - providers:
    - name: tempo
    randomSamplingPercentage: 100
  metrics:
  - providers:
    - name: prometheus
