{
 "title": "Cert Manager Certificates",
 "description": "Monitors certificates managed by cert-manager.",
 "tags": [ "cert-manager" ],
 "time": { "from": "2025-08-13T21:18:57.163Z", "to": "2025-08-13T21:28:57.163Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(exported_namespace)"
    }
   },
   {
    "name": "certificate",
    "query": {
     "query": "label_values(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\"},name)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Soonest Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\", name=~\"$certificate\"} > 0) - time()"
    }
   ]
  },
  {
   "title": "Certificate Expiration Time Left",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\", name=~\"$certificate\"} - time()) by (name,exported_namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certificates Ready Status",
   "type": "stat",
   "description": "The number of certificates in the ready state.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (condition) (certmanager_certificate_ready_status{exported_namespace=~\"$namespace\", name=~\"$certificate\"})",
     "legendFormat": "{{ condition }}"
    }
   ]
  },
  {
   "title": "Certificates Not Ready",
   "type": "table",
   "description": "Certificates that are not in a ready state may indicate a problem with the certificate configuration and should be fixed.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (exported_namespace, name)(certmanager_certificate_ready_status{exported_namespace=~\"$namespace\", name=~\"$certificate\", condition=~\"False\"}) == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certificates Past Renewal Date",
   "type": "table",
   "description": "Certificates listed here are past their renewal date. There may be a problem.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (exported_namespace, name)\n      (certmanager_certificate_renewal_timestamp_seconds{exported_namespace=~\"$namespace\", name=~\"$certificate\"}) * 1000 <= time() *1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ACME Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Overall requests per 2m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count{}[2m])) BY (status, path)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(certmanager_http_acme_client_request_count)"
    }
   ]
  }
 ]
}