prometheus: 
  alertmanager:
    enabled: false
  kube-state-metrics:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  server:
    securityContext: null # TODO this does not work with subcharts https://github.com/helm/helm/pull/12879
    global:
      scrape_interval: 15s
