---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
  namespace: {{ .Values.subscriptions.jaeger.namespace }}
spec:
  channel: {{ .Values.subscriptions.jaeger.channel }}
  installPlanApproval: {{ .Values.subscriptions.jaeger.installPlanApproval }}
  name: jaeger-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
