{{- if .Values.userWorkloadAccess.enabled }}
{{- range .Values.members }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: istio-injection-enabled
  namespace: {{ . }}
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              istio-injection: enabled
  policyTypes:
    - Ingress
...
{{- end }}
{{- end }}
