
{{- if .Values.networkpolicies.canaryUpgrades.enabled }}
{{- range .Values.members }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-istio-system
  namespace: {{ . }}
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $.Values.networkpolicies.canaryUpgrades.istioSystemNamespace }}
  policyTypes:
    - Ingress
...
{{- end }}
{{- end }}
