{{- if .Values.userWorkloadAccess.enabled }}
{{- range .Values.members }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sre-use-rules
  namespace: {{ . }}
spec:
  {{- $.Files.Get "alerts/sre-use-rules.yaml" | nindent 2 }}
...
{{- end }}
{{- end }}
