{{- if .Values.userWorkloadAccess.enabled }}
{{- range .Values.members }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: istio-sre-red-rules
  namespace: {{ . }}
spec:
  {{- $.Files.Get "alerts/istio-sre-red-rules.yaml" | nindent 2 }}
...
{{- end }}
{{- end }}
