{{- with .Values.gateway }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - {{ .host }}
  gateways:
  - {{ printf "%v/%v" .namespace .name }}
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: {{ printf "productpage.%v.svc.cluster.local" $.Release.Namespace }}
        port:
          number: 9080
{{- end }}
