{{- with .Values.gateway }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  selector:
    {{- toYaml .selector | nindent 4 }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .host }}
{{- end }}
