# needed for jmx or cryostat agent for pod-to-pod communication when mtls is enabled
{{- if or .Values.cryostat.jmx.enabled .Values.cryostat.agent.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-demo.fullname" . }}-headless
  labels:
    {{- include "spring-boot-demo.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    {{- if .Values.cryostat.agent.enabled }}
    - name: cryostat-agent
      protocol: TCP
      appProtocol: tcp
      port: 9977
      targetPort: 9977
    {{- end }}
    {{- if .Values.cryostat.jmx.enabled }}
    - name: jfr-jmx
      protocol: TCP
      appProtocol: tcp
      port: 9091
      targetPort: 9091
    {{- end }}
  selector:
    {{- include "spring-boot-demo.selectorLabels" . | nindent 4 }}
{{- end }}
