# needed for jmx or cryostat agent for pod-to-pod communication when mtls is enabled
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-demo.fullname" . }}-headless
  labels:
    {{- include "spring-boot-demo.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: cryostat-agent
      protocol: TCP
      appProtocol: tcp
      port: 9977
      targetPort: 9977
    - name: jfr-jmx
      protocol: TCP
      appProtocol: tcp
      port: 9091
      targetPort: 9091
  selector:
    {{- include "spring-boot-demo.selectorLabels" . | nindent 4 }}
