# needed for jmx or cryostat agent for pod-to-pod communication when mtls is enabled
{{- if or .Values.cryostat.headlessService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-demo.fullname" . }}-headless
  labels:
    {{- include "spring-boot-demo.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  {{- with .Values.cryostat.headlessService.ports }}
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  selector:
    {{- include "spring-boot-demo.selectorLabels" . | nindent 4 }}
{{- end }}
