apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: {{ printf "%s-%s" .Values.kiali.spec.deployment.instance_name .Values.kiali.spec.istio_namespace | quote }}
spec:
{{- with .Values.kiali.spec }}
  {{- . | toYaml | nindent 2 }}
{{- end }}
