{
 "title": "Istio Multicluster Circuit Breaker Monitoring",
 "description": "Monitor if circuit breaking occurred and traffic flowed to a different cluster. Especially useful for fail over scenarios.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(istio_requests_total,namespace)"
    }
   },
   {
    "name": "source_cluster",
    "label": "Source Cluster",
    "query": {
     "query": "label_values(istio_requests_total{namespace=~\"$namespace\"},source_cluster)"
    }
   },
   {
    "name": "destination_cluster",
    "label": "Destination Cluster",
    "query": {
     "query": "label_values(istio_requests_total{namespace=~\"$namespace\"},destination_cluster)"
    }
   },
   {
    "name": "source_app",
    "query": {
     "query": "label_values(istio_requests_total{namespace=~\"$namespace\"},source_app)"
    }
   },
   {
    "name": "destination_service",
    "query": {
     "query": "label_values(istio_requests_total{namespace=~\"$namespace\"},destination_service)"
    }
   },
   {
    "name": "response_code",
    "query": {
     "query": "label_values(istio_requests_total{namespace=~\"$namespace\"},response_code)"
    }
   },
   {
    "name": "response_flags",
    "query": {
     "query": "label_values(istio_requests_total{namespace=~\"$namespace\"},response_flags)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Istio multi-cluster requests overview",
   "type": "timeseries",
   "description": "Drill down on requests between clusters in this view.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{namespace=~\"$namespace\",source_cluster=~\"$source_cluster\", destination_cluster=~\"$destination_cluster\", source_app=~\"$source_app\", destination_service=~\"$destination_service\", response_code=~\"$response_code\", response_flags=~\"$response_flags\"}[1m])) by (destination_cluster, destination_service, response_code, response_flags, source_app)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Circuit Breaker Tripped - CRITICAL 5xx server errors",
   "type": "timeseries",
   "description": "The circuit was tripped but endpoints in the other cluster are returning 5xx server errors – the server failed to fulfill an apparently valid request.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{namespace=~\"$namespace\",source_cluster=~\"$source_cluster\", destination_cluster!~\"$source_cluster\", source_app=~\"$source_app\", destination_service=~\"$destination_service\", response_flags=~\"$response_flags\", response_code=~\"5.*\"}[1m])) by (destination_cluster, destination_service, response_code, response_flags, source_app)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Circuit Breaker Tripped - WARNING",
   "type": "timeseries",
   "description": "The circuit was tripped and the request was routed to another cluster (apparently) successfully; or at least the response is not a 5xx server error code.\nYou still should investigate why the circuit was tripped.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{namespace=~\"$namespace\",source_cluster=~\"$source_cluster\", destination_cluster!~\"$source_cluster\", source_app=~\"$source_app\", destination_service=~\"$destination_service\", response_flags=~\"$response_flags\", response_code!~\"5.*\"}[1m])) by (destination_cluster, destination_service, response_code, response_flags, source_app)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}