{{- with .Values.subscriptions.jaeger }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
  namespace: {{ .namespace }}
spec:
  channel: {{ .channel }}
  installPlanApproval: {{ .installPlanApproval }}
  name: jaeger-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}
