{{- with .Values.subscriptions.elasticsearch }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-operator
  namespace: {{ .namespace }}
spec:
  channel: {{ .channel }}
  installPlanApproval: {{ .installPlanApproval }}
  name: elasticsearch-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}
