apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali-ossm
spec:
  channel: {{ .Values.subscriptions.kiali.channel }}
  installPlanApproval: {{ .Values.subscriptions.kiali.installPlanApproval }}
  name: kiali-ossm
  source: redhat-operators
  sourceNamespace: openshift-marketplace
