{{- if .Values.tempo.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-for-tempo-{{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: '4'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  host: {{ .Values.tempo.host }}
  trafficPolicy:
    tls:
      mode: DISABLE
{{- end }}
