smcp:
  name: ossm-2-5
  namespace: istio-system
ingressgateway:
  namespace: istio-ingress
deployment:
  namespace: kiali
consoleLink: 
  enabled: true
  route: "https://kiali-istio-system.apps-crc.testing"
grafana:
  in_cluster_url: http://grafana-instance-service.istio-system.svc:3000
  url:
tracing: 
  in_cluster_url: http://tempo-minio-dev-query-frontend.tempo-system.svc.cluster.local:16685
  url:
prometheus:
  auth:
    insecure_skip_verify: true
    type: bearer
    use_kiali_token: true
  query_scope:
    mesh_id: istio-system/ossm-2-5
  url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
replicas: 1
ossmconsole:
  enabled: true
cluster_wide_access: true
accessible_namespaces: # use when cluster_wide_access is false for multi tenant config
  # - bookinfo
  # - golang-ex
  # - istio-ingress
  # - nginx-echo-headers
